# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "auth-service.name" . }}
# spec:
#   replicas: {{ .Values.replicas }}
#   selector:
#     matchLabels:
#       app: {{ include "auth-service.name" . }}
#   template:
#     metadata:
#       labels:
#         app: {{ include "auth-service.name" . }}
#     spec:
#       containers:
#       - name: auth-service
#         image: {{ include "auth-service.image" . }}
#         ports:
#         - containerPort: 4000
#         env:
#         # Secrets
#         - name: DATABASE_USER
#           valueFrom:
#             secretKeyRef:
#               name: {{ include "auth-service.name" . }}-db-secret
#               key: DATABASE_USER
#         - name: DATABASE_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: {{ include "auth-service.name" . }}-db-secret
#               key: DATABASE_PASSWORD
#         - name: DATABASE_DBNAME
#           valueFrom:
#             secretKeyRef:
#               name: {{ include "auth-service.name" . }}-db-secret
#               key: DATABASE_DBNAME
#         - name: DATABASE_PORT
#           valueFrom:
#             secretKeyRef:
#               name: {{ include "auth-service.name" . }}-db-secret
#               key: DATABASE_PORT
#         # ConfigMap
#         - name: DATABASE_HOST
#           valueFrom:
#             configMapKeyRef:
#               name: {{ include "auth-service.name" . }}-config
#               key: DATABASE_HOST
#         # Construct full URL
#         - name: DATABASE_URL
#           value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_DBNAME)"