apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.name" . }}-external-secret
  namespace:  "{{ .Values.namespace }}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: {{ include "auth-service.name" . }}-db-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: albert-dev-rds-credentials
    
  